### ISSUE TITLE
panic: interface conversion: ast.Stmt is *ast.AssignStmt, not *ast.BlockStmt

### ISSUE THREAD

**Issue by zeyujiang** [NickyBoy89/java2go#3]
INFO[0000] Collecting files...                          
INFO[0000] Parsing ASTs...                              
INFO[0000] Generating symbol tables...                  
INFO[0000] Resolving symbols...                         
INFO[0000] Converting files...                          
INFO[0000] Converting file "Copynumber.java"            
panic: interface conversion: ast.Stmt is *ast.AssignStmt, not *ast.BlockStmt

goroutine 1 [running]:
main.TryParseStmt(0xc000121d10, {0xc0000d8000, 0x919e, 0x919f}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0xc0000f0080, {0x0, ...}})
	.../statement.go:208 +0x527e
main.TryParseStmt(0xc000121c80, {0xc0000d8000, 0x919e, 0x919f}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0xc0000f0080, {0x0, ...}})
	.../statement.go:154 +0x4ad5
main.ParseStmt(0xc000121c80, {0xc0000d8000?, 0x0?, 0x40ab3d?}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0xc0000f0080, {0x0, ...}})
	.../statement.go:15 +0x6e
main.ParseNode(0xc0000a15f0, {0xc0000d8000, 0x919e, 0x919f}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0xc0000f0080, {0x0, ...}})
	.../tree_sitter.go:203 +0x719
main.TryParseStmt(0xc0000a1290, {0xc0000d8000, 0x919e, 0x919f}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0xc0000f0080, {0x0, ...}})
	.../statement.go:158 +0x4bee
main.ParseStmt(0xc0000a1290, {0xc0000d8000?, 0x0?, 0x0?}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0xc0000f0080, {0x0, ...}})
	.../statement.go:15 +0x6e
main.ParseDecl(0xc0000a0d20, {0xc0000d8000, 0x919e, 0x919f}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0xc0000f0080, {0x0, ...}})
	.../declaration.go:206 +0x78e
main.ParseDecls(0xc0000a0c60, {0xc0000d8000, 0x919e, 0x919f}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0x0, {0x0, ...}})
	.../declaration.go:106 +0x25cd
main.ParseDecls(0xc0000a06f0, {0xc0000d8000, 0x919e, 0x919f}, {{0xc0000bc200, 0xa}, 0xc000111060, 0xc0000940a0, 0x0, {0x0, ...}})
	.../declaration.go:90 +0x1505
main.ParseNode(0xc0000a0450, {0xc0000d8000, 0x919e, 0x919f}, {{0x0, 0x0}, 0xc000111060, 0xc0000940a0, 0x0, {0x0, ...}})
	.../tree_sitter.go:89 +0x3425
main.main()
	.../java2go.go:224 +0xfa5

**Comment by NickyBoy89** [comment]
Hi, thank you for opening an issue! In the future, I would have asked for a small reproducible example, but the crash location was enough to fix this. I have just fixed this in b435ddf4ce43c762e9a7faeaf36fa27e52749fd8, but it was an issue with the handling of inline if statements like the following:

```java
if (condition) something;
```
